name: Build and Deploy to Cloud Run


on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: django-admin-uzafir-cloudrun
  SECRET_KEY: ${{ secrets.DJANGO_SECRET }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  INSTANCE_NAME: ${{ secrets.INSTANCE_NAME }}
  SOCKET_NAME: ${{ secrets.SOCKET_NAME}}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      # Setup gcloud CLI
      - name: Connect to gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
      
      
      # Build and push image to Google Container Registry
      - name: Delete-Image
        run: |-
          gcloud auth configure-docker
          gcloud container images delete gcr.io/$PROJECT_ID/$SERVICE_NAME:Latest --quiet
      
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:Latest"
          
  
      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:Latest" \
            --platform "managed" \
            --allow-unauthenticated \
            --set-env-vars "DJANGO_SECRET=$SECRET_KEY" \
            --set-env-vars "INSTANCE_UNIX_SOCKET=$SOCKET_NAME" \
            --set-env-vars "INSTANCE_CONNECTION_NAME=$INSTANCE_NAME" \
            --set-env-vars "DB_NAME=$DB_NAME" \
            --set-env-vars "DB_USER=$DB_USER" \
            --set-env-vars "DB_PASS=$DB_PASS"
        
        